name: monorepo PR
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.9.0
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: SETUP COREPACK
        run: corepack enable

      - name: SETUP NODE.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SETUP YARN
        run: yarn set version stable

      - name: INSTALL
        run: yarn install --immutable

      - name: BUILD
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run build

      - name: LINT
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run lint:check

      - name: TEST
        run: yarn workspaces foreach -Rpt --from '{char-info,parjs}' run test:coverage

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          plugin: noop
          directory: packages/char-info/coverage
          flags: char-info

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: packages/parjs/coverage
          flags: parjs
          plugin: noop
